[package]
name = "retcode"
version = "1.0.0"
edition = "2018"
license = "BSD-3-Clause"
authors = ["Avery R. <contact@nekodjin.xyz>"]
homepage = "https://github.com/nekodjin/retcode"
description = "Exits with a given exit code."

